### PR TITLE
Game area players stacked

### PR DESCRIPTION
**Pull request by derrickbeining**
Important things to note:
- added queryUserPlayerNum().then(setUserPlayerNumInRedux), to resetReduxForPendingGameInstance because playerNum wasn't being set when game refreshed
- added a func to dropValidators.js to prevent users from being able to drop their cards on other players' solitaire stacks (we previously only addressed dragging other players' cards)
- extracted most of the styling out of components and added to SCSS

### CODE REVIEW

**Review by sjhelba — DISMISSED** [review]
Getting the same errors Jess is

**Review by jess010 — CHANGES_REQUESTED** [review]
Styling looks good (love the diamond display for draggable stacks), but I'm getting "Type error: 'Cards' is undefined" error preventing the game from loading on the browser of the last player to join the game. Can you address this before we merge this in?

**Comment by derrickbeining** [comment]
@jess010 , I wasn't able to produce that particular error, but I do get errors sometimes when I have multiple browsers open during game initialization. I believe this is because we have not corrected the issue where each client is actually executing the game init sequence, including generating randomized decks, which means firebase is getting flooded with 4x the amount of data it should, with conflicting data (every client is trying to store its own set of 4 randomized decks), and its trying to update all 4 clients with that superfluous conflicting data in real time. React doesn't seem to like this barrage of updates. 

I'm not sure how to correct this issue right now without some major refactoring of the app. Everything works fine if you only have one browser open when the game init sequence runs, and then have everyone join the game after that.

As far as the "Cards is undefined" error, I'm not sure how to fix it if I can't reproduce it.

**Review by sjhelba — APPROVED** [review]
Need to fix bug where reload is necessary

**Review by jess010 — APPROVED** [review]

**Pull request merged**
